"""добавил_поля__source_и_facts_в_модель_complaints

Revision ID: a1cf66d3992a
Revises: bddcc50cc074
Create Date: 2026-07-11 13:53:20.494633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1cf66d3992a'
down_revision: Union[str, Sequence[str], None] = 'bddcc50cc074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('complaints', sa.Column('extracted_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('complaints', 'structured_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('complaints', 'ai_summary',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'ai_summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('complaints', 'structured_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('complaints', 'extracted_facts')
    op.drop_column('complaints', 'source')
    # ### end Alembic commands ###
