"""add_height_and_weight_to_patient

Revision ID: bddcc50cc074
Revises: 0153ecc35249
Create Date: 2026-07-04 17:32:04.212840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bddcc50cc074'
down_revision: Union[str, Sequence[str], None] = '0153ecc35249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('weight_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'weight_kg')
    op.drop_column('patients', 'height_cm')
    # ### end Alembic commands ###
